<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>genbil</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\s*#\s*region|^\s*/\*|^(?![^{]*?//|[^{]*?/\*(?!.*?\*/.*?\{)).*?\{\s*($|//|/\*(?!.*?\*/.*\S))</string>
	<key>foldingStopMarker</key>
	<string>^\s*#\s*endregion|^\s*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~C</string>
	<key>name</key>
	<string>GenbiL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#code</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>code</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
        <dict>
					<key>include</key>
					<string>#areas</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#actions</string>
				</dict>
        <dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
        <dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#qualifiers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
			</array>
		</dict>
    <key>block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.begin.source.genbil</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.end.source.genbil</string>
						</dict>
					</dict>
					<key>name</key>
					<string>keyword.operator.source.genbil</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
    <key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>///</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.source.genbil</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.block.documentation.source.genbil</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.xml</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.source.genbil</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/\n?</string>
					<key>name</key>
					<string>comment.block.source.genbil</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.source.genbil</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.line.double-slash.source.genbil</string>
				</dict>
			</array>
		</dict>
		<key>areas</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(case|template|setting|suite)\b</string>
					<key>name</key>
					<string>storage.type.source.genbil</string>
				</dict>
			</array>
		</dict>
    <key>actions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(set|load|save|scope|copy|merge|cross|add|remove|hold|rename|move|replace|substitute|concatenate|separate|filter|group|reduce|split|generate|save|include|addrange|reference|default)\b</string>
					<key>name</key>
					<string>storage.modifier.source.genbil</string>
				</dict>
			</array>
		</dict>
    <key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(not|equal|like)\b</string>
					<key>name</key>
					<string>entity.name.function.genbil</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(empty|left|right|off)\b</string>
					<key>name</key>
					<string>entity.name.type.genbil</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.source.genbil</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.source.genbil</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.source.genbil</string>
				</dict>
			</array>
		</dict>
    <key>qualifiers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(file|query|distinct|predefined|vector|folder|grouping|sut|assert|connectionString)\b</string>
					<key>name</key>
					<string>keyword.control.source.genbil</string>
				</dict>
			</array>
		</dict>
    <key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(column|values|on|as|with|into|to|in|out|when)\b</string>
					<key>name</key>
					<string>keyword.operator.source.genbil</string>
				</dict>
			</array>
		</dict>

		
	</dict>
	<key>scopeName</key>
	<string>source.genbil</string>
	<key>uuid</key>
	<string>2BA75B32-707C-11D9-A928-000D93589AF6</string>
</dict>
</plist>
